### ISSUE TITLE
Preserve log colors

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-nano#2]
### Expected Behavior / Situation

Colors emitted in webpack logs are preserved

### Actual Behavior / Situation

Colors are not preserved by `webpack-nano`.

### Modification Proposal

It's a minor thing, but the colors make the logs easier to read:

![ss 2018-12-04 at 11 17 22](https://user-images.githubusercontent.com/3151613/49405054-3b8cec80-f7b6-11e8-8574-6c8835ef5ba7.png)

vs.

![ss 2018-12-04 at 11 15 28](https://user-images.githubusercontent.com/3151613/49405058-3d56b000-f7b6-11e8-9948-a84fdcebe075.jpg)

**Comment by shellscape** [comment]
@G-Rath looks like your environment might have an issue with `chalk` and it's `supportsColor` method: https://github.com/shellscape/webpack-nano/blob/198bb130a8d81a4871036a9dcaafb0cac4320935/bin/wp.js#L127

This might be a situation in which we need your help to debug. I'm unable to reproduce it on my end.

**Comment by G-Rath** [comment]
@shellscape probably, but that was why I made the issue, as it's a bug for my environment. Sorry about not mentioning I was on Windows - I had meant to do that.

I'm running Windows 10 Pro, and as my screenshots show, webpacks colors work fine 😉

**Comment by shellscape** [comment]
Cool.

> webpacks colors work fine

You mean _webpack-cli_ displays colors just fine 😉  We use `chalk`, and `chalk` uses `supports-color` under the hood. webpack-cli also uses `supports-color`

Are you sure that your config isn't messing with that value in some way? (Perhaps webpack-cli is overriding that?)

Give this a shot as well to make sure that the module thinks your env does in fact support color:

- `$ npm install --global supports-color-cli`
- `$ supports-color`
- `$ echo $?` - I'm not sure about this one on windows.

`$?` displays the exit code of the last command. If the exit code is `1` then that module thinks your env doesn't support colors. 

Aside from all that, we probably need you to inspect that line 127 I pasted before, to see what the return value of `chalk.supportsColor` is there.

**Comment by G-Rath** [comment]
`echo %errorlevel%` is the [Windows version](https://stackoverflow.com/questions/334879/how-do-i-get-the-application-exit-code-from-a-windows-command-line) of `echo $?`.

Mine echos `9009`.

I'll take a look into logging the output of that line.

**Comment by G-Rath** [comment]
I added this line above the one you mentioned to `webpack-nano`:

`log.info(`supports color: ${JSON.stringify(chalk.supportsColor)}`);`

The results:
`⬡ webpack: supports color: {"level":3,"hasBasic":true,"has256":true,"has16m":true}`.

Since `webpack-nano` & `awesome-typescript-loader` both have color, I'd say the issue might lie with `webpack` (and surrounding components)?

**Comment by shellscape** [comment]
This is 🍌 s. What's the value of `(options.stats == null ? defaultStatsOptions : options.stats)`  on line 133?

**Comment by G-Rath** [comment]
That's the problem: I have `stats` in my config, which isn't merged, meaning `colors` is lost:

`stats: { assetsSort: '!chunks' },`

**Comment by PlayMa256** [comment]
Interesting that on that screenshot I posted, I didn't have colors anywhere on my config, not an argument to the cli. Whatelse could it be?

**Comment by shellscape** [comment]
@PlayMa256 if you didn't define stats options in the config, webpack-nano uses a small default set of options, which turns on color if supported.

**Comment by PlayMa256** [comment]
Oh, so nvm. Makes sense

**Comment by G-Rath** [comment]
> Now with webpack-nano, I chose to leave out the opinionated stuff

I knew that was going to be your response :) I did notice that `colors` is `false` by default, and so on.

I'd argue that `colors` might be the one you should be slightly opinionated on, as like I said in the original post webpacks color-less output is very painful to try and read at a glance, and given that you already test if the terminal supports color, it makes for a great default, and saves the user from having to have an extra package in userland + "clever" logic in their webpack configs.

However I also understand that it's a very slippery slope, with as you said its walking a very fine line.

Ultimately, `webpack-nano` is looking to be a very cool & speedy package.

My only other problem/bug with it right now is that it doesn't seem to output anything indicating it's noticed a file change - it just seems to output a blank line? But I'm unsure if that's a problem sitting with `webpack-nano`, `webpack-serve-plugin`, etc, and I don't really have the time to make a minimal example repo for a bug report 😕

**Comment by G-Rath** [comment]
@shellscape 

> I use this (webpack-nano) with webpack-plugin-serve almost exclusively

Do you also use `hmr` almost exclusively? I've had a couple of minor bugs that I suspect are from it, but again I've not had the time to report due to the need for a minimal example repo.

For me, setting `hmr` to `false` results in a client error, while when it is actually enabled it never works when I make actual code changes, instead just giving me `Aborted because uC5Q is not accepted` in the Chrome console, and then finally if I have `liveReload` set to true, it works better, but I usually get `Error [ERR_STREAM_WRITE_AFTER_END]: write after end` after every re-compilation in the build console (the build & everything works fine - it's just extra noise that I have to filter out when looking over the results).

I suspect that last one might be b/c the page reload means the socket discussions, but `hmr` still tries to use it, or something along those lines.

If you'd like to discuss these problems further, it might be easier take this to a chatroom or email-chain. Otherwise right now they're not preventing me from developing, and they might already be on your radar.

Thanks regardless 😄 

(btw, I'm pretty sure these are `webpack-serve-plugin` bugs, rather than `webpack-nano` ones)
