### ISSUE TITLE
Webpack Mode not propagate?!

### ISSUE THREAD

**Issue by martinoppitz** [shellscape/webpack-nano#23]
![image](https://user-images.githubusercontent.com/6279703/99204434-f18c4e00-27b5-11eb-9330-88f8094291af.png)

**Comment by shellscape** [comment]
Our issue templates are required

**Comment by martinoppitz** [comment]
@shellscape sometimes we can edit a desc ... if there is a misstake.

It is 2:54 am and it was a short note.

**Comment by TrySound** [comment]
@martinoppitz Also see here https://github.com/shellscape/webpack-nano#usage. There is no `--mode` option.
