### ISSUE TITLE
webpack-nano package.json possible fix?

### ISSUE THREAD

**Issue by bawinkler** [shellscape/webpack-nano#24]
- Webpack Version: 5.6.0
- Operating System (or Browser): Windows 10 / Firefox Developer
- Node Version: 14.15.1
- webpack-nano Version: Current

### How Do We Reproduce?
I simply installed the latest webpack 5.6.0 then tried to install webpack-nano --save-dev and it lists the peer dependency as webpack 4.42.2 which is what I see being called in package.json, however, not sure how to get this to work

### Expected Behavior
install webpack nano = no errors

### Actual Behavior
doesn't install says cannot find peer dependency webpack 4.42.2

**Comment by bawinkler** [comment]
version 4.20.2

**Comment by shellscape** [comment]
Fixed in #22
