### ISSUE TITLE
Allow webpack.config.babel.js

### ISSUE THREAD

**Issue by j-walker23** [shellscape/webpack-nano#5]
First I want to say thank you so damn much for this and `webpack-plugin-serve`. I am brand new to webpack. Trying to convert large `angularjs` app from `jspm`. In only a couple hours I had the entire app building and loading but I was about to give up after 30 straight hours of trying to get HMR working with a server processed index.html and https proxy. The in memory of WDS just destroyed me. And right at the very end, I find you talking about being done with `webpack-serve`. A github profile click later and I find the `webpack-plugin-serve` gem. In about 10 mins I have a completed build process with great HMR. So thank you, I just became a Patreon, and i've never been more happy to.

### Expected Behavior / Situation
Since I am still so new, not sure if this is possible. But i figured i'd give it a shot. Plus i wanted to thank you anyway. I can still bypass `webpack-nano` using `npx webpack --config webpack.config.babel.js`.

Allow webpack.config.babel.js either through default no config, or `--config webpack.config.babel.js`

### Actual Behavior / Situation
First import in config from command `npx wp --config webpack.config.babel.js throws `SyntaxError: Unexpected identifier`.

### Modification Proposal
Looking in `webpack` source is daunting so I'm not sure. But hopefully this package can do what `npx webpack --config webpack.config.babel.js` does.

**Comment by shellscape** [comment]
you're welcome! thank _you_ for the kind words and becoming a patron!

The proposal sounds like a win to me. I'll start looking into how to accomplish it. I'm not a huge fan of how webpack-cli went about supporting that feature, so I'd like to find a different/better way.
